/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 omnifret-gplayer contributors.
 */

package com.omnifret.gplayer.raster.test

import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.addressOf
import kotlinx.cinterop.usePinned
import platform.Foundation.NSData
import platform.Foundation.dataWithContentsOfFile
import platform.posix.memcpy

/**
 * Resolve test resources via [IOS_RASTER_TEST_RESOURCES_PATH], a build-
 * time constant generated by `:gplayer-raster-skiko:generateIosTestResourcePath`.
 * Same approach as `:gplayer`'s iOS fixture loader.
 */
@OptIn(ExperimentalForeignApi::class)
internal actual fun loadRasterTestResource(path: String): ByteArray {
    val full = "$IOS_RASTER_TEST_RESOURCES_PATH/$path"
    val data = NSData.dataWithContentsOfFile(full)
        ?: error("raster test resource not found: $full")
    val length = data.length.toInt()
    val bytes = ByteArray(length)
    if (length > 0) {
        bytes.usePinned { pinned ->
            memcpy(pinned.addressOf(0), data.bytes, length.toULong())
        }
    }
    return bytes
}
