// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering
import com.omnifret.gplayer.core.*

/**
 * This eventargs define the details about the rendering and layouting process and are
 * provided whenever a part of of the music sheet is rendered.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class RenderFinishedEventArgs
{
    /**
     * Gets or sets the unique id of this event args.
     */
    public var id: String = com.omnifret.gplayer.model.ModelUtils.newGuid()
    
    
    /**
     * A value indicating whether the currently rendered viewport can be reused.
     */
    public var reuseViewport: Boolean = true
    
    
    /**
     * Gets or sets the x position of the current rendering result.
     */
    public var x: Double = 0.0
    
    
    /**
     * Gets or sets the y position of the current rendering result.
     */
    public var y: Double = 0.0
    
    
    /**
     * Gets or sets the width of the current rendering result.
     */
    public var width: Double = 0.0
    
    
    /**
     * Gets or sets the height of the current rendering result.
     */
    public var height: Double = 0.0
    
    
    /**
     * Gets or sets the currently known total width of the final music sheet.
     */
    public var totalWidth: Double = 0.0
    
    
    /**
     * Gets or sets the currently known total height of the final music sheet.
     */
    public var totalHeight: Double = 0.0
    
    
    /**
     * Gets or sets the index of the first masterbar that was rendered in this result.
     */
    public var firstMasterBarIndex: Double = -1.0
    
    
    /**
     * Gets or sets the index of the last masterbar that was rendered in this result.
     */
    public var lastMasterBarIndex: Double = -1.0
    
    
    /**
     * Gets or sets the render engine specific result object which contains the rendered music sheet.
     */
    public var renderResult: Any? = null


    // KMP-PORT: per-master-bar x-offsets within this chunk, in scaled CSS px,
    // populated by the layout engine. Consumed by ScoreRasterRenderer (in
    // :gplayer-raster-skiko) so raster consumers can place a playhead or
    // resolve tap-to-bar without walking the canvas output. The SVG path
    // ignores it. Null when the layout doesn't supply per-bar positions
    // (e.g. score info / chord diagram chunks that contain no bars).
    public var barXOffsets: Map<Int, Double>? = null


    public constructor()
}

