import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.library)
    alias(libs.plugins.compose)
    alias(libs.plugins.compose.compiler)
}

group = "com.omnifret"
version = "0.1.0-SNAPSHOT"

// Test resource staging mirroring :gplayer's pattern. commonTest/resources
// doesn't reach the Android JVM unit-test classpath nor the Kotlin/Native
// iOS test executable on its own. Stage explicitly:
//   - Android: mirror commonTest/resources into src/androidUnitTest/
//     resources, which AGP scans (.gitignored).
//   - iOS: stage into a build dir and bake the absolute path into a
//     generated Kotlin constant.
val rasterTestResourcesDir = layout.buildDirectory.dir("raster-test-resources")
val syncRasterTestResources = tasks.register<Sync>("syncRasterTestResources") {
    from("src/commonTest/resources")
    into(rasterTestResourcesDir)
}

val syncRasterAndroidTestResources = tasks.register<Sync>("syncRasterAndroidTestResources") {
    from("src/commonTest/resources")
    into("src/androidUnitTest/resources")
}

val iosTestResourcePathSrc = layout.buildDirectory.dir("generated/iosTestResourcePath/kotlin")
val generateIosTestResourcePath = tasks.register("generateIosTestResourcePath") {
    val outDir = iosTestResourcePathSrc
    val pathProvider = rasterTestResourcesDir.map { it.asFile.absolutePath }
    inputs.property("path", pathProvider)
    outputs.dir(outDir)
    dependsOn(syncRasterTestResources)
    doLast {
        val dir = outDir.get().asFile.resolve("com/omnifret/gplayer/raster/test")
        dir.mkdirs()
        dir.resolve("RasterFixturesPath.kt").writeText(
            """
            // Generated by :gplayer-raster-skiko:generateIosTestResourcePath. Do not edit.
            package com.omnifret.gplayer.raster.test

            internal const val IOS_RASTER_TEST_RESOURCES_PATH: String = "${pathProvider.get()}"
            """.trimIndent() + "\n",
        )
    }
}

kotlin {
    jvmToolchain(17)

    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    listOf(iosArm64(), iosSimulatorArm64(), iosX64()).forEach { target ->
        target.binaries.framework {
            baseName = "OmniFretGplayerRasterSkiko"
            isStatic = true
        }
    }

    applyDefaultHierarchyTemplate()

    sourceSets {
        commonMain {
            dependencies {
                api(project(":gplayer"))
                // The Compose Compiler plugin (required since Compose MP 1.6.10)
                // checks for the runtime on the classpath even when no @Composable
                // functions are used. We don't actually need the runtime at this
                // module's call sites — but the version check fails without it.
                implementation(libs.compose.runtime)
                implementation(libs.compose.ui.graphics)
                implementation(libs.compose.ui.text)
            }
        }
        commonTest {
            dependencies {
                implementation(kotlin("test"))
            }
        }
        androidUnitTest {
            resources.srcDir("src/commonTest/resources")
        }
        iosTest {
            kotlin.srcDir(iosTestResourcePathSrc)
        }
    }
}

android {
    namespace = "com.omnifret.gplayer.raster.skiko"
    compileSdk = 35
    defaultConfig {
        minSdk = 26
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeTest>()
    .configureEach {
        dependsOn(syncRasterTestResources, generateIosTestResourcePath)
    }

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinNativeCompile>()
    .matching { it.name.contains("Test") && it.name.contains("Ios") }
    .configureEach {
        dependsOn(generateIosTestResourcePath)
    }

afterEvaluate {
    tasks.matching { it.name == "processDebugUnitTestJavaRes" || it.name == "processReleaseUnitTestJavaRes" }
        .configureEach {
            dependsOn(syncRasterAndroidTestResources)
        }

    // Android JVM unit tests can't run on this module without Robolectric:
    // PlatformTextSupport calls Typeface.Builder().build() at canvas
    // construction, and the stubbed Android framework throws "Method
    // not mocked" for every Typeface API. The meaningful verification
    // lives in iosSimulatorArm64Test (real skiko) plus consumer-side
    // instrumented tests on Android. Disable the JVM unit-test tasks
    // here so `./gradlew build` stays green; bring them back via
    // Robolectric if/when there's a need.
    tasks.matching { it.name == "testDebugUnitTest" || it.name == "testReleaseUnitTest" }
        .configureEach { enabled = false }
}
