// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer
import com.omnifret.gplayer.core.*

/**
 * This public class represents the global the library environment where
 * the library looks for information like available layout engines
 * staves etc.
 * This public class represents the global the library environment where
 * the library looks for information like available layout engines
 * staves etc.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class Environment
{
    companion object{
        /**
         * The scaling factor to use when rending raster graphics for sharper rendering on high-dpi displays.
         */
        @kotlin.jvm.JvmStatic
        internal var highDpiFactor: Double = 1.0
        
        
        /**
         */
        @kotlin.jvm.JvmStatic
        private fun _appendScriptName(url: String): String{
            var paramurl = url
            if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(paramurl)) && !paramurl.endsWith(".js")))
            {
                if (!paramurl.endsWith("/"))
                {
                    paramurl += "/"
                }
                paramurl += "com.omnifret.gplayer.js"
            }
            return paramurl
        }
        
        @kotlin.jvm.JvmStatic
        public var renderEngines: com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.RenderEngineFactory> = com.omnifret.gplayer.Environment._createDefaultRenderEngines()
        
        
        @kotlin.jvm.JvmStatic
        internal var layoutEngines: com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.LayoutMode, com.omnifret.gplayer.LayoutEngineFactory> = com.omnifret.gplayer.Environment._createDefaultLayoutEngines()
        
        
        @kotlin.jvm.JvmStatic
        internal var staveProfiles: com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.StaveProfile, com.omnifret.gplayer.core.ecmaScript.Set<String>> = com.omnifret.gplayer.Environment._createDefaultStaveProfiles()
        
        
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun getRenderEngineFactory(engine: String): com.omnifret.gplayer.RenderEngineFactory{
            if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(engine)) || !com.omnifret.gplayer.Environment.renderEngines.has(engine))
            {
                return com.omnifret.gplayer.Environment.renderEngines.get("default")!!
            }
            return com.omnifret.gplayer.Environment.renderEngines.get(engine)!!
        }
        
        /**
         */
        @kotlin.jvm.JvmStatic
        internal fun getLayoutEngineFactory(layoutMode: com.omnifret.gplayer.LayoutMode): com.omnifret.gplayer.LayoutEngineFactory{
            if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(layoutMode)) || !com.omnifret.gplayer.Environment.layoutEngines.has(layoutMode))
            {
                return com.omnifret.gplayer.Environment.layoutEngines.get(com.omnifret.gplayer.LayoutMode.Page)!!
            }
            return com.omnifret.gplayer.Environment.layoutEngines.get(layoutMode)!!
        }
        
        /**
         * Gets all default ScoreImporters
         */
        @kotlin.jvm.JvmStatic
        public fun buildImporters(): com.omnifret.gplayer.collections.List<com.omnifret.gplayer.importer.ScoreImporter>{
            return com.omnifret.gplayer.collections.List<com.omnifret.gplayer.importer.ScoreImporter>(
                com.omnifret.gplayer.importer.Gp3To5Importer(), 
                com.omnifret.gplayer.importer.GpxImporter(), 
                com.omnifret.gplayer.importer.Gp7To8Importer(), 
                com.omnifret.gplayer.importer.MusicXmlImporter(), 
                com.omnifret.gplayer.importer.CapellaImporter(), 
                com.omnifret.gplayer.importer.GPlayerTexImporter())
            
        }
        
        @kotlin.jvm.JvmStatic
        private fun _createDefaultRenderEngines(): com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.RenderEngineFactory>{
            var renderEngines: com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.RenderEngineFactory> = com.omnifret.gplayer.collections.Map<String, com.omnifret.gplayer.RenderEngineFactory>()
            renderEngines.set("svg", com.omnifret.gplayer.RenderEngineFactory(true, fun(): com.omnifret.gplayer.platform.svg.CssFontSvgCanvas{
                return com.omnifret.gplayer.platform.svg.CssFontSvgCanvas()
            }
            ))
            renderEngines.set("default", renderEngines.get("svg")!!)
            // KMP-PORT: removed the gplayerSkia engine. GPlayerSkia is JVM/JNI-
            // only; iOS gets its own ICanvas via Phase 3
            // (Compose Canvas for Android, CoreGraphics for iOS).
            //
            // Update (2026): the sibling :gplayer-raster-skiko module ships
            // a ComposeRasterCanvas (ICanvas backed by Compose Multiplatform's
            // androidx.compose.ui.graphics.Canvas — Skia-rendered on iOS via
            // skiko, android.graphics.Canvas on Android) registered at runtime
            // via Environment.renderEngines.set(...) for the duration of
            // each ScoreRasterRenderer.render() call. Consumers wanting raster
            // output should depend on :gplayer-raster-skiko; the Phase 3
            // platform-specific path remains an option for non-Compose
            // consumers but is no longer the default direction.
            com.omnifret.gplayer.EnvironmentPartials._createPlatformSpecificRenderEngines(renderEngines)
            return renderEngines
        }

        // KMP-PORT: enableGPlayerSkia / registerGPlayerSkiaCustomFont removed
        // along with the skia engine. Reintroduce an expect/actual binding
        // here if GPlayerSkia ever ships a Kotlin/Native target.
        
        @kotlin.jvm.JvmStatic
        internal var defaultRenderers: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.BarRendererFactory> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.BarRendererFactory>(
            com.omnifret.gplayer.rendering.SlashBarRendererFactory(com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.EffectBandInfo>(
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.TempoEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.TripletFeelEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.MarkerEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.DirectionsEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.FreeTimeEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.TextEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.BeatTimerEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.ChordsEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.AlternateEndingsEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop, order = 1000.0))
            ), com.omnifret.gplayer.rendering.ScoreBarRendererFactory(com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.EffectBandInfo>(
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.CapoEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.FermataEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.BeatBarreEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.NoteOrnamentEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.RasgueadoEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.WahPedalEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.WhammyBarEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.SimpleDipWhammyBarEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.TrillEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.OttaviaEffectInfo(true), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.LeftHandTapEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.TapEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.WideBeatVibratoEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.SlightBeatVibratoEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.WideNoteVibratoEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.SlightNoteVibratoEffectInfo(false), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.FadeEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop, shouldCreate = fun(staff: com.omnifret.gplayer.model.Staff): Boolean{
                    return !staff.showTablature
                }
                ), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.LetRingEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop, shouldCreate = fun(staff: com.omnifret.gplayer.model.Staff): Boolean{
                    return !staff.showTablature
                }
                ), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.PickStrokeEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop, shouldCreate = fun(staff: com.omnifret.gplayer.model.Staff): Boolean{
                    return !staff.showTablature
                }
                ), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.PickSlideEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop, shouldCreate = fun(staff: com.omnifret.gplayer.model.Staff): Boolean{
                    return !staff.showTablature
                }
                ), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.GolpeEffectInfo(com.omnifret.gplayer.model.GolpeType.Finger), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.GolpeEffectInfo(com.omnifret.gplayer.model.GolpeType.Thumb), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedBottom), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.CrescendoEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedBottom), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.DynamicsEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedBottom), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.SustainPedalEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedBottom))
            ), com.omnifret.gplayer.rendering.NumberedBarRendererFactory(com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.EffectBandInfo>(
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.NumberedBarKeySignatureEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop, order = 1000.0))
            ), com.omnifret.gplayer.rendering.TabBarRendererFactory(com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.EffectBandInfo>(
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.LyricsEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.SharedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.TabWhammyEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.TrillEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.WideBeatVibratoEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.SlightBeatVibratoEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.WideNoteVibratoEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.SlightNoteVibratoEffectInfo(true), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.TapEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.FadeEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.HarmonicsEffectInfo(com.omnifret.gplayer.model.HarmonicType.Natural), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.HarmonicsEffectInfo(com.omnifret.gplayer.model.HarmonicType.Artificial), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.HarmonicsEffectInfo(com.omnifret.gplayer.model.HarmonicType.Pinch), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.HarmonicsEffectInfo(com.omnifret.gplayer.model.HarmonicType.Tap), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.HarmonicsEffectInfo(com.omnifret.gplayer.model.HarmonicType.Semi), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.HarmonicsEffectInfo(com.omnifret.gplayer.model.HarmonicType.Feedback), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.LetRingEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.FingeringEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.PalmMuteEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.PickStrokeEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.PickSlideEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.LeftHandTapEffectInfo(), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.GolpeEffectInfo(com.omnifret.gplayer.model.GolpeType.Finger), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedTop, shouldCreate = fun(staff: com.omnifret.gplayer.model.Staff): Boolean{
                    return !staff.showStandardNotation
                }
                ), 
                
                com.omnifret.gplayer.rendering.EffectBandInfo(effect = com.omnifret.gplayer.rendering.effects.GolpeEffectInfo(com.omnifret.gplayer.model.GolpeType.Thumb), mode = com.omnifret.gplayer.rendering.EffectBandMode.OwnedBottom, shouldCreate = fun(staff: com.omnifret.gplayer.model.Staff): Boolean{
                    return !staff.showStandardNotation
                }
                ))
            ))
        
        
        
        @kotlin.jvm.JvmStatic
        private fun _createDefaultStaveProfiles(): com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.StaveProfile, com.omnifret.gplayer.core.ecmaScript.Set<String>>{
            var staveProfiles: com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.StaveProfile, com.omnifret.gplayer.core.ecmaScript.Set<String>> = com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.StaveProfile, com.omnifret.gplayer.core.ecmaScript.Set<String>>()
            staveProfiles.set(com.omnifret.gplayer.StaveProfile.Default, com.omnifret.gplayer.core.ecmaScript.Set<String>(com.omnifret.gplayer.collections.SimpleIterable<String>(
                com.omnifret.gplayer.rendering.SlashBarRenderer.StaffId, com.omnifret.gplayer.rendering.ScoreBarRenderer.StaffId, com.omnifret.gplayer.rendering.NumberedBarRenderer.StaffId, com.omnifret.gplayer.rendering.TabBarRenderer.StaffId)
            ))
            staveProfiles.set(com.omnifret.gplayer.StaveProfile.ScoreTab, com.omnifret.gplayer.core.ecmaScript.Set<String>(com.omnifret.gplayer.collections.SimpleIterable<String>(
                com.omnifret.gplayer.rendering.SlashBarRenderer.StaffId, com.omnifret.gplayer.rendering.ScoreBarRenderer.StaffId, com.omnifret.gplayer.rendering.NumberedBarRenderer.StaffId, com.omnifret.gplayer.rendering.TabBarRenderer.StaffId)
            ))
            staveProfiles.set(com.omnifret.gplayer.StaveProfile.Score, com.omnifret.gplayer.core.ecmaScript.Set<String>(com.omnifret.gplayer.collections.SimpleIterable<String>(
                com.omnifret.gplayer.rendering.ScoreBarRenderer.StaffId)
            ))
            staveProfiles.set(com.omnifret.gplayer.StaveProfile.Tab, com.omnifret.gplayer.core.ecmaScript.Set<String>(com.omnifret.gplayer.collections.SimpleIterable<String>(
                com.omnifret.gplayer.rendering.TabBarRenderer.StaffId)
            ))
            staveProfiles.set(com.omnifret.gplayer.StaveProfile.TabMixed, com.omnifret.gplayer.core.ecmaScript.Set<String>(com.omnifret.gplayer.collections.SimpleIterable<String>(
                com.omnifret.gplayer.rendering.TabBarRenderer.StaffId)
            ))
            return staveProfiles
        }
        
        @kotlin.jvm.JvmStatic
        private fun _createDefaultLayoutEngines(): com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.LayoutMode, com.omnifret.gplayer.LayoutEngineFactory>{
            var engines: com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.LayoutMode, com.omnifret.gplayer.LayoutEngineFactory> = com.omnifret.gplayer.collections.Map<com.omnifret.gplayer.LayoutMode, com.omnifret.gplayer.LayoutEngineFactory>()
            engines.set(com.omnifret.gplayer.LayoutMode.Page, com.omnifret.gplayer.LayoutEngineFactory(true, fun(r: com.omnifret.gplayer.rendering.ScoreRenderer): com.omnifret.gplayer.rendering.layout.PageViewLayout{
                return com.omnifret.gplayer.rendering.layout.PageViewLayout(r)
            }
            ))
            engines.set(com.omnifret.gplayer.LayoutMode.Horizontal, com.omnifret.gplayer.LayoutEngineFactory(false, fun(r: com.omnifret.gplayer.rendering.ScoreRenderer): com.omnifret.gplayer.rendering.layout.HorizontalScreenLayout{
                return com.omnifret.gplayer.rendering.layout.HorizontalScreenLayout(r)
            }
            ))
            engines.set(com.omnifret.gplayer.LayoutMode.Parchment, com.omnifret.gplayer.LayoutEngineFactory(true, fun(r: com.omnifret.gplayer.rendering.ScoreRenderer): com.omnifret.gplayer.rendering.layout.ParchmentLayout{
                return com.omnifret.gplayer.rendering.layout.ParchmentLayout(r)
            }
            ))
            return engines
        }
        
        /**
         * Prints the environment information for easier troubleshooting.
         * @param force Whether to force printing.
         */
        @kotlin.jvm.JvmStatic
        public fun printEnvironmentInfo(force: Boolean = true): Unit{
            var printer: ((arg1: String) -> Unit) = if(force)  fun(message: String): Unit{
                com.omnifret.gplayer.Logger.log.debug("VersionInfo", message)
            }
             else fun(message: String): Unit{
                com.omnifret.gplayer.Logger.debug("VersionInfo", message)
            }
            
            com.omnifret.gplayer.generated.VersionInfo.print(printer)
            printer("""High DPI: ${(com.omnifret.gplayer.Environment.highDpiFactor).toTemplate()}""")
            com.omnifret.gplayer.EnvironmentPartials._printPlatformInfo(printer)
        }
        
    }
    public constructor()
}

/**
 * A factory for custom layout engines.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class LayoutEngineFactory
{
    /**
     * Whether the layout is considered "vertical" (affects mainly scrolling behavior).
     */
    public var vertical: Boolean
    
    /**
     * Creates a new layout instance.
     */
    public var createLayout: ((arg1: com.omnifret.gplayer.rendering.ScoreRenderer) -> com.omnifret.gplayer.rendering.layout.ScoreLayout)
    
    public constructor(vertical: Boolean, createLayout: ((arg1: com.omnifret.gplayer.rendering.ScoreRenderer) -> com.omnifret.gplayer.rendering.layout.ScoreLayout)){
        this.vertical = vertical
        this.createLayout = createLayout
    }
    
}

/**
 * A factory for custom render engines.
 * Note for Web: To use a custom engine in workers you have to ensure the engine and registration to the environment are
 * also done in the background worker files (e.g. when bundling)
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class RenderEngineFactory
{
    /**
     * Whether the layout supports background workers.
     */
    public var supportsWorkers: Boolean
    
    public var createCanvas: (() -> com.omnifret.gplayer.platform.ICanvas)
    
    public constructor(supportsWorkers: Boolean, canvas: (() -> com.omnifret.gplayer.platform.ICanvas)){
        this.supportsWorkers = supportsWorkers
        this.createCanvas = canvas
    }
    
}

