// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.layout
import com.omnifret.gplayer.core.*

/**
 * This layout arranges the bars all horizontally
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class HorizontalScreenLayout: com.omnifret.gplayer.rendering.layout.ScoreLayout
{
    private var _system: com.omnifret.gplayer.rendering.staves.StaffSystem? = null
    
    public override val name: String
    get(){
        return "HorizontalScreen"
    }
    
    public override val supportsResize: Boolean
    get(){
        return false
    }
    
    public override val firstBarX: Double
    get(){
        var x: Double = this.pagePadding!![(0).toInt()]
        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this._system)))
        {
            x += this._system!!.accoladeWidth
        }
        return x
    }
    
    public override fun doResize(): Unit{
    }
    
    /**
     */
    public override fun doUpdateForBars(_renderHints: com.omnifret.gplayer.rendering.RenderHints): Boolean{
        return false
    }
    
    /**
     */
    protected override fun doLayoutAndRender(renderHints: com.omnifret.gplayer.rendering.RenderHints?): Unit{
        var score: com.omnifret.gplayer.model.Score = this.renderer.score!!
        var startIndex: Double = this.renderer.settings.display.startBar
        startIndex--
        startIndex = com.omnifret.gplayer.core.ecmaScript.Math.min(score.masterBars.length - (1.0).toDouble(), com.omnifret.gplayer.core.ecmaScript.Math.max(0.0, startIndex))
        var currentBarIndex: Double = startIndex
        var endBarIndex: Double = this.renderer.settings.display.barCount
        if (endBarIndex <= 0)
        {
            endBarIndex = score.masterBars.length
        }
        endBarIndex = startIndex + endBarIndex - (1.0).toDouble()
        endBarIndex = com.omnifret.gplayer.core.ecmaScript.Math.min(score.masterBars.length - (1.0).toDouble(), com.omnifret.gplayer.core.ecmaScript.Math.max(0.0, endBarIndex))
        this._system = this.createEmptyStaffSystem(0.0)
        this._system!!.shareMinDurationAcrossBars = false
        this._system!!.isLast = true
        this._system!!.x = this.pagePadding!![(0).toInt()]
        this._system!!.y = this.pagePadding!![(1).toInt()]
        var countPerPartial: Double = this.renderer.settings.display.barCountPerPartial
        var partials: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.layout.HorizontalScreenLayoutPartialInfo> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.layout.HorizontalScreenLayoutPartialInfo>(
        )
        
        var currentPartial: com.omnifret.gplayer.rendering.layout.HorizontalScreenLayoutPartialInfo = com.omnifret.gplayer.rendering.layout.HorizontalScreenLayoutPartialInfo()
        while (currentBarIndex <= endBarIndex)
        {
            var multiBarRestInfo: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.collections.DoubleList>? = this.multiBarRestInfo
            var additionalMultiBarsRestBarIndices: com.omnifret.gplayer.collections.DoubleList? = if(multiBarRestInfo != null && multiBarRestInfo!!.has(currentBarIndex))  multiBarRestInfo!!.get(currentBarIndex)!! else null
            var result: com.omnifret.gplayer.rendering.staves.MasterBarsRenderers = this._system!!.addBars(this.renderer.tracks!!, currentBarIndex, additionalMultiBarsRestBarIndices)
            if (currentPartial.masterBars.length >= countPerPartial && !result.isLinkedToPrevious)
            {
                currentPartial = this._completePartial(partials, currentPartial)
            }
            this._scaleBars(result)
            currentPartial.results.push(result)
            currentPartial.masterBars.push(score.masterBars[(currentBarIndex).toInt()])
            currentPartial.width += result.width
            currentBarIndex++
        }
        if (currentPartial.masterBars.length > 0)
        {
            this._completePartial(partials, currentPartial)
        }
        this._finalizeStaffSystem()
        this.height = com.omnifret.gplayer.core.ecmaScript.Math.floor(this._system!!.y + this._system!!.height)
        this.width = this._system!!.x + this._system!!.width + this.pagePadding!![(2).toInt()]
        currentBarIndex = 0.0
        var x: Double = 0.0
        if (true) {
            var i: Double = 0.0
            
            while(i < partials.length){
                var partial: com.omnifret.gplayer.rendering.layout.HorizontalScreenLayoutPartialInfo = partials[(i).toInt()]
                var e: com.omnifret.gplayer.rendering.RenderFinishedEventArgs = com.omnifret.gplayer.rendering.RenderFinishedEventArgs()
                e.reuseViewport = renderHints?.reuseViewport ?: false
                e.x = x
                e.y = 0.0
                e.totalWidth = this.width
                e.totalHeight = this.height
                e.width = partial.width
                e.height = this.height
                e.firstMasterBarIndex = partial.masterBars[(0).toInt()].index
                e.lastMasterBarIndex = partial.masterBars[(partial.masterBars.length - (1.0).toDouble()).toInt()].index
                x += partial.width
                var partialBarIndex: Double = currentBarIndex
                var partialIndex: Double = i
                this._system!!.buildBoundingsLookup(0.0, 0.0)
                // KMP-PORT: populate per-bar **first-beat** x-offsets in chunk-
                // local logical pixels for raster consumers. Mirrors the painter
                // translation below: partial 0 paints with cx=-(-system.x)=system.x,
                // partial p>0 paints with cx=-(getBarX(firstBar)+accoladeWidth).
                //
                // Uses the bounds lookup (already populated by the
                // `buildBoundingsLookup(0.0, 0.0)` call above) to read the
                // **actual rendered first-beat visualBounds.x**. This is the
                // same source alphaTab's CursorHandler uses for cursor
                // placement, so the playhead lands on whatever pixel column
                // the renderer actually drew the first beat at — including
                // any offsets from accidentals, bar numbers, or staff
                // alignment that an analytical formula would miss.
                //
                // The bounds lookup stores positions in the (cx=0, cy=0)
                // coordinate frame of `buildBoundingsLookup`, which for
                // partial 0 corresponds to canvas-local pixels (the painter
                // translates the system by +system.x to draw at
                // canvas_x = system.x + system_local_x — and bounds were
                // built with system.x as their origin). For partials p>0
                // we subtract the partial's own canvas origin to re-base
                // into chunk-local coords.
                //
                // Falls back to the analytical `beatGlyphsStart` if the
                // bounds lookup is unavailable (e.g. empty score, builds
                // skipped, future regressions in the lookup chain) so a
                // flawed bounds path can't crash playback. Upstream to
                // alphaTab once the regen pipeline lands.
                val displayScale: Double = this.renderer.settings.display.scale
                val firstBarIdx: Int = partial.masterBars[(0).toInt()].index.toInt()
                val lastBarIdx: Int = partial.masterBars[
                    (partial.masterBars.length - (1.0).toDouble()).toInt()
                ].index.toInt()
                val accoladeW: Double = this._system!!.accoladeWidth
                val systemX: Double = this._system!!.x
                val firstBarStaffX: Double =
                    this._system!!.getBarX(firstBarIdx.toDouble())
                val track = this.renderer.tracks!![(0).toInt()]
                val staffId = this._system!!.allStaves[(0).toInt()].staffId
                val boundsLookup = this.renderer.boundsLookup
                val cursorBounds = boundsLookup
                    ?.findMasterBarByIndex(firstBarIdx.toDouble())
                    ?.visualBounds
                if (cursorBounds != null) {
                    e.cursorTopPx = cursorBounds.y * displayScale
                    e.cursorHeightPx = cursorBounds.h * displayScale
                }
                val offsets = HashMap<Int, Double>()
                val beatOffsets = ArrayList<DoubleArray>()
                for (barIdx in firstBarIdx..lastBarIdx) {
                    val bar = track.staves[(0).toInt()].bars[(barIdx).toInt()]
                    val barRenderer = this.getRendererForBar(staffId, bar)!!
                    // Look up the rendered first-beat bounds in the system-
                    // origin coordinate frame.
                    val firstBeat = if (
                        bar.voices.length > 0 &&
                        bar.voices[(0).toInt()].beats.length > 0
                    ) bar.voices[(0).toInt()].beats[(0).toInt()] else null
                    val beatBoundsX: Double? = if (boundsLookup != null && firstBeat != null) {
                        boundsLookup.findBeat(firstBeat)?.visualBounds?.x
                    } else null
                    val canvasX: Double = when {
                        // Bounds-lookup path: visualBounds.x is in system-origin
                        // coords (= partial-0 canvas coords). For partial 0
                        // pass through; for partial p>0 re-base by subtracting
                        // the partial's own canvas origin (= getBarX(firstBar)
                        // + accoladeW − system.x, which simplifies after
                        // mirroring the painter's renderX).
                        beatBoundsX != null && i == 0.0 -> beatBoundsX
                        beatBoundsX != null -> beatBoundsX - (firstBarStaffX + accoladeW)
                        // Analytical fallback (matches the old formula).
                        i == 0.0 ->
                            systemX + accoladeW + barRenderer.x + barRenderer.beatGlyphsStart
                        else ->
                            barRenderer.x - firstBarStaffX + barRenderer.beatGlyphsStart
                    }
                    offsets[barIdx] = canvasX * displayScale

                    // Per-beat positions. Use `OnNotes` (the post-
                    // accidental, pre-notehead anchor) so the engraved
                    // x matches when the audio engine attacks the note.
                    // Each beat's chunk-canvas x = canvasX + (getBeatX
                    // - beatGlyphsStart). Beats accumulate into the
                    // chunk-global list; sorted ascending by tick once
                    // the bar loop finishes.
                    if (bar.voices.length > 0) {
                        val voice = bar.voices[(0).toInt()]
                        for (bi in 0 until voice.beats.length.toInt()) {
                            val beat = voice.beats[(bi).toInt()]
                            val tick = beat.absoluteDisplayStart
                            val beatLocalX = barRenderer.getBeatX(
                                beat,
                                com.omnifret.gplayer.rendering.BeatXPosition.OnNotes,
                                false,
                            )
                            val beatCanvasX = canvasX + (beatLocalX - barRenderer.beatGlyphsStart)
                            beatOffsets.add(doubleArrayOf(tick, beatCanvasX * displayScale))
                        }
                    }
                }
                beatOffsets.sortBy { it[(0).toInt()] }
                // Trailing anchor at the partial's right edge so the
                // playhead glides forward during the final note's
                // duration rather than parking at the last engraved
                // beat. tick = end of the last bar's playback; x =
                // partial width.
                if (lastBarIdx >= firstBarIdx) {
                    val lastBar = track.staves[(0).toInt()].bars[(lastBarIdx).toInt()]
                    val lastBarEndTick = lastBar.masterBar.start +
                        lastBar.masterBar.calculateDuration(true)
                    beatOffsets.add(doubleArrayOf(lastBarEndTick, e.width))
                }
                e.barXOffsets = offsets
                e.beatXOffsets = beatOffsets
                this.registerPartial(e, fun(canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
                    var renderX: Double = this._system!!.getBarX(partial.masterBars[(0).toInt()].index) + this._system!!.accoladeWidth
                    if (partialIndex == 0.0)
                    {
                        renderX -= this._system!!.x + this._system!!.accoladeWidth
                    }
                    canvas.color = this.renderer.settings.display.resources.mainGlyphColor
                    canvas.textAlign = com.omnifret.gplayer.platform.TextAlign.Left
                    com.omnifret.gplayer.Logger.debug(this.name, """Rendering partial from bar ${(partial.masterBars[(0).toInt()].index).toTemplate()} to ${(partial.masterBars[(partial.masterBars.length - (1.0).toDouble()).toInt()].index).toTemplate()}""", null)
                    this._system!!.paintPartial(-renderX, this._system!!.y, canvas, partialBarIndex, partial.masterBars.length)
                }
                )
                currentBarIndex += partial.masterBars.length
                i++
            }
        }
        this.height = this.layoutAndRenderBottomScoreInfo(this.height)
        this.height = this._layoutAndRenderAnnotation(this.height)
        this.height += this.pagePadding!![(3).toInt()]
        this.height *= this.renderer.settings.display.scale
    }
    
    /**
     */
    private fun _scaleBars(result: com.omnifret.gplayer.rendering.staves.MasterBarsRenderers): Unit{
        result.width = 0.0
        this._system!!.width -= result.width
        for (r in result.renderers)
        {
            var barDisplayWidth: Double = if(r.staff!!.system.staves.length > 1)  r.bar.masterBar.displayWidth else r.bar.displayWidth
            if (barDisplayWidth > 0)
            {
                r.scaleToWidth(barDisplayWidth)
            }
            var w: Double = r.x + r.width
            if (w > result.width)
            {
                result.width = w
            }
        }
        this._system!!.width += result.width
    }
    
    /**
     */
    private fun _completePartial(partials: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.layout.HorizontalScreenLayoutPartialInfo>, currentPartial: com.omnifret.gplayer.rendering.layout.HorizontalScreenLayoutPartialInfo): com.omnifret.gplayer.rendering.layout.HorizontalScreenLayoutPartialInfo{
        if (partials.length == 0.0)
        {
            currentPartial.width += this._system!!.accoladeWidth + this.pagePadding!![(0).toInt()]
        }
        partials.push(currentPartial)
        com.omnifret.gplayer.Logger.debug(this.name, """Finished partial from bar ${(currentPartial.masterBars[(0).toInt()].index).toTemplate()} to ${(currentPartial.masterBars[(currentPartial.masterBars.length - (1.0).toDouble()).toInt()].index).toTemplate()}""", null)
        var newPartial: com.omnifret.gplayer.rendering.layout.HorizontalScreenLayoutPartialInfo = com.omnifret.gplayer.rendering.layout.HorizontalScreenLayoutPartialInfo()
        newPartial.x = currentPartial.x + currentPartial.width
        return newPartial
    }
    
    private fun _finalizeStaffSystem(): Unit{
        this._alignRenderers()
        this._system!!.finalizeSystem()
    }
    
    private fun _alignRenderers(): Unit{
        this.width = 0.0
        var system: com.omnifret.gplayer.rendering.staves.StaffSystem = this._system!!
        for (s in system.allStaves)
        {
            s.resetSharedLayoutData()
            var w: Double = 0.0
            for (renderer in s.barRenderers)
            {
                renderer.x = w
                renderer.y = s.topPadding + s.topOverflow
                renderer.scaleToWidth(renderer.width)
                w += renderer.width
            }
            if (w > this.width)
            {
                system.width = w
            }
        }
        system.width += system.accoladeWidth
    }
    
    public constructor(renderer: com.omnifret.gplayer.rendering.ScoreRenderer)
        : super(renderer)
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal class HorizontalScreenLayoutPartialInfo
{
    public var x: Double = 0.0
    
    
    public var width: Double = 0.0
    
    
    public var masterBars: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.model.MasterBar> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.model.MasterBar>(
    )
    
    
    
    public var results: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.staves.MasterBarsRenderers> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.staves.MasterBarsRenderers>(
    )
    
    
    
    public constructor()
}
