// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package com.omnifret.gplayer.rendering.layout
import com.omnifret.gplayer.core.*

/**
 * Base layout for page and parchment style layouts where we have an endless
 * vertical page with fitted systems.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
internal abstract class VerticalLayoutBase: com.omnifret.gplayer.rendering.layout.ScoreLayout
{
    private var _systems: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.staves.StaffSystem> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.staves.StaffSystem>(
    )
    
    
    private var _allMasterBarRenderers: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.staves.MasterBarsRenderers> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.staves.MasterBarsRenderers>(
    )
    
    
    private var _barsFromPreviousSystem: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.staves.MasterBarsRenderers> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.staves.MasterBarsRenderers>(
    )
    
    
    private var _reuseViewPort: Boolean = false
    
    private var _preSystemPartialIds: com.omnifret.gplayer.collections.List<String> = com.omnifret.gplayer.collections.List<String>(
    )
    
    
    private var _systemPartialIds: com.omnifret.gplayer.collections.List<String> = com.omnifret.gplayer.collections.List<String>(
    )
    
    
    /**
     */
    protected override fun doLayoutAndRender(renderHints: com.omnifret.gplayer.rendering.RenderHints?): Unit{
        var y: Double = this.pagePadding!![(1).toInt()]
        this.width = this.renderer.width
        this._allMasterBarRenderers = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.staves.MasterBarsRenderers>(
        )
        
        this._preSystemPartialIds = com.omnifret.gplayer.collections.List<String>(
        )
        
        this._systemPartialIds = com.omnifret.gplayer.collections.List<String>(
        )
        
        this._reuseViewPort = renderHints?.reuseViewport ?: false
        this._systems = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.staves.StaffSystem>(
        )
        
        y = this._layoutAndRenderScoreInfo(y, -1.0)
        y = this._layoutAndRenderTunings(y, -1.0)
        y = this._layoutAndRenderChordDiagrams(y, -1.0)
        y = this._layoutAndRenderScore(y, this.firstBarIndex)
        y = this.layoutAndRenderBottomScoreInfo(y)
        y = this._layoutAndRenderAnnotation(y)
        this.height = (y + this.pagePadding!![(3).toInt()]) * this.renderer.settings.display.scale
    }
    
    /**
     */
    protected override fun registerPartial(args: com.omnifret.gplayer.rendering.RenderFinishedEventArgs, callback: ((arg1: com.omnifret.gplayer.platform.ICanvas) -> Unit)): Unit{
        args.reuseViewport = this._reuseViewPort
        super.registerPartial(args, callback)
    }
    
    /**
     */
    protected fun reregisterPartial(id: String): Unit{
        var args: com.omnifret.gplayer.rendering.RenderFinishedEventArgs? = this.getExistingPartialArgs(id)
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(args)))
        {
            return
        }
        args!!.reuseViewport = this._reuseViewPort
        ((this.renderer.partialLayoutFinished as com.omnifret.gplayer.EventEmitterOfT<com.omnifret.gplayer.rendering.RenderFinishedEventArgs>)).trigger(args!!)
    }
    
    public override val supportsResize: Boolean
    get(){
        return true
    }
    
    public override val firstBarX: Double
    get(){
        var x: Double = this.pagePadding!![(0).toInt()]
        if (this._systems.length > 0)
        {
            x += this._systems[(0).toInt()].accoladeWidth
        }
        return x
    }
    
    /**
     */
    public override fun doUpdateForBars(renderHints: com.omnifret.gplayer.rendering.RenderHints): Boolean{
        this._reuseViewPort = renderHints.reuseViewport ?: false
        var firstModifiedMasterBar: Double = renderHints.firstChangedMasterBar!!
        var systemIndex: Double = this._systems.findIndex(fun(s: com.omnifret.gplayer.rendering.staves.StaffSystem): Boolean{
            var first: Double = s.masterBarsRenderers[(0).toInt()].masterBar.index
            var last: Double = s.masterBarsRenderers[(s.masterBarsRenderers.length - (1.0).toDouble()).toInt()].masterBar.index
            return first <= firstModifiedMasterBar && firstModifiedMasterBar <= last
        }
        )
        if (systemIndex == -1.0 || !this.renderer.settings.core.enableLazyLoading)
        {
            return false
        }
        var firstRebuiltBarIndex: Double = this._systems[(systemIndex).toInt()].masterBarsRenderers[(0).toInt()].masterBar.index
        this.renderer.boundsLookup!!.clearFromMasterBar(firstRebuiltBarIndex)
        var removeSystems: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.staves.StaffSystem> = this._systems.splice(systemIndex, this._systems.length - systemIndex)
        this._systemPartialIds.splice(systemIndex, this._systemPartialIds.length - systemIndex)
        var system: com.omnifret.gplayer.rendering.staves.StaffSystem = removeSystems[(0).toInt()]
        var y: Double = system.y
        var firstBarIndex: Double = system.masterBarsRenderers[(0).toInt()].masterBar.index
        for (preSystemPartial in this._preSystemPartialIds)
        {
            this.reregisterPartial(preSystemPartial)
        }
        if (true) {
            var i: Double = 0.0
            
            while(i < systemIndex){
                this.reregisterPartial(this._systemPartialIds[(i).toInt()])
                i++
            }
        }
        y = this._layoutAndRenderScore(y, firstBarIndex)
        y = this.layoutAndRenderBottomScoreInfo(y)
        y = this._layoutAndRenderAnnotation(y)
        this.height = (y + this.pagePadding!![(3).toInt()]) * this.renderer.settings.display.scale
        return true
    }
    
    public override fun doResize(): Unit{
        var y: Double = this.pagePadding!![(1).toInt()]
        this.width = this.renderer.width
        var oldHeight: Double = this.height
        this._reuseViewPort = true
        y = this._layoutAndRenderScoreInfo(y, oldHeight)
        y = this._layoutAndRenderTunings(y, oldHeight)
        y = this._layoutAndRenderChordDiagrams(y, oldHeight)
        y = this._resizeAndRenderScore(y, oldHeight)
        y = this.layoutAndRenderBottomScoreInfo(y)
        y = this._layoutAndRenderAnnotation(y)
        this.height = (y + this.pagePadding!![(3).toInt()]) * this.renderer.settings.display.scale
    }
    
    /**
     */
    private fun _layoutAndRenderTunings(y: Double, totalHeight: Double = -1.0): Double{
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.tuningGlyph)))
        {
            return y
        }
        var res: com.omnifret.gplayer.RenderingResources = this.renderer.settings.display.resources
        this.tuningGlyph!!.x = this.pagePadding!![(0).toInt()]
        this.tuningGlyph!!.width = this.scaledWidth - this.pagePadding!![(0).toInt()] - this.pagePadding!![(2).toInt()]
        this.tuningGlyph!!.doLayout()
        var tuningHeight: Double = com.omnifret.gplayer.core.ecmaScript.Math.round(this.tuningGlyph!!.height)
        var e: com.omnifret.gplayer.rendering.RenderFinishedEventArgs = com.omnifret.gplayer.rendering.RenderFinishedEventArgs()
        e.x = 0.0
        e.y = y
        e.width = this.scaledWidth
        e.height = tuningHeight
        e.totalWidth = this.scaledWidth
        e.totalHeight = if(totalHeight < 0)  y + e.height else totalHeight
        this.registerPartial(e, fun(canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
            canvas.color = res.scoreInfoColor
            canvas.textAlign = com.omnifret.gplayer.platform.TextAlign.Center
            this.tuningGlyph!!.paint(0.0, 0.0, canvas)
        }
        )
        this._preSystemPartialIds.push(e.id)
        return y + tuningHeight
    }
    
    /**
     */
    private fun _layoutAndRenderChordDiagrams(y: Double, totalHeight: Double = -1.0): Double{
        if (!com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(this.chordDiagrams)))
        {
            return y
        }
        var res: com.omnifret.gplayer.RenderingResources = this.renderer.settings.display.resources
        this.chordDiagrams!!.x = this.pagePadding!![(0).toInt()]
        this.chordDiagrams!!.width = this.scaledWidth - this.pagePadding!![(0).toInt()] - this.pagePadding!![(2).toInt()]
        this.chordDiagrams!!.doLayout()
        var diagramHeight: Double = com.omnifret.gplayer.core.ecmaScript.Math.round(this.chordDiagrams!!.height)
        var e: com.omnifret.gplayer.rendering.RenderFinishedEventArgs = com.omnifret.gplayer.rendering.RenderFinishedEventArgs()
        e.x = 0.0
        e.y = y
        e.width = this.scaledWidth
        e.height = diagramHeight
        e.totalWidth = this.scaledWidth
        e.totalHeight = if(totalHeight < 0)  y + diagramHeight else totalHeight
        this.registerPartial(e, fun(canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
            canvas.color = res.scoreInfoColor
            canvas.textAlign = com.omnifret.gplayer.platform.TextAlign.Center
            this.chordDiagrams!!.paint(0.0, 0.0, canvas)
        }
        )
        this._preSystemPartialIds.push(e.id)
        return y + diagramHeight
    }
    
    /**
     */
    private fun _layoutAndRenderScoreInfo(y: Double, totalHeight: Double = -1.0): Double{
        com.omnifret.gplayer.Logger.debug(this.name, "Layouting score info")
        var e: com.omnifret.gplayer.rendering.RenderFinishedEventArgs = com.omnifret.gplayer.rendering.RenderFinishedEventArgs()
        e.x = 0.0
        e.y = y
        var infoHeight: Double = 0.0
        var res: com.omnifret.gplayer.RenderingResources = this.renderer.settings.display.resources
        var scoreInfoGlyphs: com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.TextGlyph> = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.glyphs.TextGlyph>(
        )
        
        for ((scoreElement, _notationElement) in com.omnifret.gplayer.rendering.layout.ScoreLayout.headerElements.value)
        {
            if (this.headerGlyphs.has(scoreElement))
            {
                var glyph: com.omnifret.gplayer.rendering.glyphs.TextGlyph = this.headerGlyphs.get(scoreElement)!!
                glyph.y = infoHeight
                this.alignScoreInfoGlyph(glyph)
                var lineHeight: Double = glyph.font.size
                if (scoreElement == com.omnifret.gplayer.model.ScoreSubElement.Words)
                {
                    if (this.headerGlyphs.has(com.omnifret.gplayer.model.ScoreSubElement.Music))
                    {
                        var musicGlyph: com.omnifret.gplayer.rendering.glyphs.TextGlyph = this.headerGlyphs.get(com.omnifret.gplayer.model.ScoreSubElement.Music)!!
                        if (musicGlyph.textAlign != glyph.textAlign)
                        {
                            lineHeight = 0.0
                        }
                    }
                }
                infoHeight += lineHeight
                scoreInfoGlyphs.push(glyph)
            }
        }
        if (scoreInfoGlyphs.length > 0)
        {
            infoHeight = com.omnifret.gplayer.core.ecmaScript.Math.floor(infoHeight + 17.0)
            e.width = this.scaledWidth
            e.height = infoHeight
            e.totalWidth = this.scaledWidth
            e.totalHeight = if(totalHeight < 0)  y + e.height else totalHeight
            this.registerPartial(e, fun(canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
                canvas.color = res.scoreInfoColor
                canvas.textAlign = com.omnifret.gplayer.platform.TextAlign.Center
                for (g in scoreInfoGlyphs)
                {
                    g.paint(0.0, 0.0, canvas)
                }
            }
            )
            this._preSystemPartialIds.push(e.id)
        }
        return y + infoHeight
    }
    
    /**
     */
    private fun _resizeAndRenderScore(y: Double, oldHeight: Double): Double{
        var paramy = y
        var barsPerRowActive: Boolean = this.getBarsPerSystem(0.0) > 0
        this._systemPartialIds = com.omnifret.gplayer.collections.List<String>(
        )
        
        if (barsPerRowActive)
        {
            if (true) {
                var i: Double = 0.0
                
                while(i < this._systems.length){
                    var system: com.omnifret.gplayer.rendering.staves.StaffSystem = this._systems[(i).toInt()]
                    system.width = system.computedWidth
                    this._fitSystem(system)
                    paramy += this._paintSystem(system, oldHeight)
                    i++
                }
            }
        }
        else 
        {
            for (r in this._allMasterBarRenderers)
            {
                for (b in r.renderers)
                {
                    b.afterReverted()
                }
            }
            this._systems = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.staves.StaffSystem>(
            )
            
            var currentIndex: Double = 0.0
            var maxWidth: Double = this._maxWidth
            var system: com.omnifret.gplayer.rendering.staves.StaffSystem = this.createEmptyStaffSystem(this._systems.length)
            system.x = this.pagePadding!![(0).toInt()]
            system.y = paramy
            while (currentIndex < this._allMasterBarRenderers.length)
            {
                var renderers: com.omnifret.gplayer.rendering.staves.MasterBarsRenderers? = this._allMasterBarRenderers[(currentIndex).toInt()]
                if (system.width + renderers!!.width <= maxWidth || system.masterBarsRenderers.length == 0.0)
                {
                    system.addMasterBarRenderers(this.renderer.tracks!!, renderers!!)
                    currentIndex++
                    if (this._needsLineBreak(currentIndex))
                    {
                        system.isFull = true
                    }
                }
                else 
                {
                    while (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(renderers)) && !renderers!!.canWrap) && system.masterBarsRenderers.length > 1))
                    {
                        renderers = system.revertLastBar()
                        currentIndex--
                    }
                    system.isFull = true
                }
                if (system.isFull)
                {
                    system.isLast = this.lastBarIndex == system.lastBarIndex
                    this._systems.push(system)
                    this._fitSystem(system)
                    paramy += this._paintSystem(system, oldHeight)
                    system = this.createEmptyStaffSystem(this._systems.length)
                    system.x = this.pagePadding!![(0).toInt()]
                    system.y = paramy
                }
            }
            system.isLast = this.lastBarIndex == system.lastBarIndex
            this._fitSystem(system)
            paramy += this._paintSystem(system, oldHeight)
        }
        return paramy
    }
    
    /**
     */
    private fun _layoutAndRenderScore(y: Double, startIndex: Double): Double{
        var paramy = y
        var currentBarIndex: Double = startIndex
        var endBarIndex: Double = this.lastBarIndex
        while (currentBarIndex <= endBarIndex)
        {
            var system: com.omnifret.gplayer.rendering.staves.StaffSystem = this._createStaffSystem(currentBarIndex, endBarIndex)
            this._systems.push(system)
            system.x = this.pagePadding!![(0).toInt()]
            system.y = paramy
            currentBarIndex = system.lastBarIndex + 1.0
            this._fitSystem(system)
            com.omnifret.gplayer.Logger.debug(this.name, """Rendering partial from bar ${(system.firstBarIndex).toTemplate()} to ${(system.lastBarIndex).toTemplate()}""", null)
            paramy += this._paintSystem(system, paramy)
        }
        return paramy
    }
    
    /**
     */
    private fun _paintSystem(system: com.omnifret.gplayer.rendering.staves.StaffSystem, totalHeight: Double): Double{
        var height: Double = com.omnifret.gplayer.core.ecmaScript.Math.floor(system.height)
        var args: com.omnifret.gplayer.rendering.RenderFinishedEventArgs = com.omnifret.gplayer.rendering.RenderFinishedEventArgs()
        args.x = 0.0
        args.y = system.y
        args.totalWidth = this.scaledWidth
        args.totalHeight = totalHeight
        args.width = this.scaledWidth
        args.height = height
        args.firstMasterBarIndex = system.firstBarIndex
        args.lastMasterBarIndex = system.lastBarIndex
        system.buildBoundingsLookup(0.0, 0.0)
        // KMP-PORT: populate per-bar x-offsets for raster consumers (see
        // RenderFinishedEventArgs.barXOffsets). system.getBarX returns
        // unscaled coords; multiply by display.scale so the values share
        // units with args.width (which registerPartial scales below).
        val displayScale: Double = this.renderer.settings.display.scale
        val offsets = HashMap<Int, Double>()
        val firstIdx: Int = system.firstBarIndex.toInt()
        val lastIdx: Int = system.lastBarIndex.toInt()
        for (i in firstIdx..lastIdx) {
            offsets[i] = system.getBarX(i.toDouble()) * displayScale
        }
        args.barXOffsets = offsets
        this.registerPartial(args, fun(canvas: com.omnifret.gplayer.platform.ICanvas): Unit{
            this.renderer.canvas!!.color = this.renderer.settings.display.resources.mainGlyphColor
            this.renderer.canvas!!.textAlign = com.omnifret.gplayer.platform.TextAlign.Left
            system.paint(0.0, -(args.y / this.renderer.settings.display.scale), canvas)
        }
        )
        this._systemPartialIds.push(args.id)
        return height
    }
    
    /**
     * Realignes the bars in this line according to the available space
     */
    private fun _fitSystem(system: com.omnifret.gplayer.rendering.staves.StaffSystem): Unit{
        system.reconcileMinDurationIfDirty()
        if (system.isFull || system.width > this._maxWidth || this.renderer.settings.display.justifyLastSystem)
        {
            this._scaleToWidth(system, this._maxWidth)
        }
        else 
        {
            this._scaleToWidth(system, system.width)
        }
        system.finalizeSystem()
    }
    
    protected abstract val shouldApplyBarScale: Boolean
    
    /**
     */
    private fun _scaleToWidth(system: com.omnifret.gplayer.rendering.staves.StaffSystem, width: Double): Unit{
        var staffWidth: Double = width - system.accoladeWidth
        var shouldApplyBarScale: Boolean = this.shouldApplyBarScale
        var weightTotal: Double = if(shouldApplyBarScale)  system.totalBarDisplayScale else system.totalContentWidth
        var distributable: Double = com.omnifret.gplayer.core.ecmaScript.Math.max(0.0, staffWidth - system.totalFixedOverhead)
        var contentShare: Double = if(weightTotal > 0)  distributable / weightTotal else 0.0
        for (s in system.allStaves)
        {
            s.resetSharedLayoutData()
            var w: Double = 0.0
            if (true) {
                var i: Double = 0.0
                
                while(i < s.barRenderers.length){
                    var renderer: com.omnifret.gplayer.rendering.BarRendererBase = s.barRenderers[(i).toInt()]
                    var mb: com.omnifret.gplayer.rendering.staves.MasterBarsRenderers = system.masterBarsRenderers[(i).toInt()]
                    renderer.x = w
                    renderer.y = s.topPadding + s.topOverflow
                    var weight: Double = if(shouldApplyBarScale)  system.getBarDisplayScale(renderer) else mb.maxContentWidth
                    var actualBarWidth: Double = mb.maxFixedOverhead + weight * contentShare
                    renderer.scaleToWidth(actualBarWidth)
                    w += renderer.width
                    i++
                }
            }
        }
        system.width = width
    }
    
    /**
     */
    protected abstract fun getBarsPerSystem(systemIndex: Double): Double
    
    /**
     */
    private fun _createStaffSystem(currentBarIndex: Double, endIndex: Double): com.omnifret.gplayer.rendering.staves.StaffSystem{
        var system: com.omnifret.gplayer.rendering.staves.StaffSystem = this.createEmptyStaffSystem(this._systems.length)
        var barsPerRow: Double = this.getBarsPerSystem(system.index)
        var maxWidth: Double = this._maxWidth
        var end: Double = endIndex + 1.0
        var barIndex: Double = currentBarIndex
        while (barIndex < end)
        {
            if (this._barsFromPreviousSystem.length > 0)
            {
                for (renderer in this._barsFromPreviousSystem)
                {
                    system.addMasterBarRenderers(this.renderer.tracks!!, renderer)
                    barIndex = renderer.lastMasterBarIndex
                }
            }
            else 
            {
                var multiBarRestInfo: com.omnifret.gplayer.collections.DoubleObjectMap<com.omnifret.gplayer.collections.DoubleList>? = this.multiBarRestInfo
                var additionalMultiBarsRestBarIndices: com.omnifret.gplayer.collections.DoubleList? = if(multiBarRestInfo != null && multiBarRestInfo!!.has(barIndex))  multiBarRestInfo!!.get(barIndex)!! else null
                var renderers: com.omnifret.gplayer.rendering.staves.MasterBarsRenderers = system.addBars(this.renderer.tracks!!, barIndex, additionalMultiBarsRestBarIndices)
                this._allMasterBarRenderers.push(renderers)
                barIndex = renderers.lastMasterBarIndex
            }
            this._barsFromPreviousSystem = com.omnifret.gplayer.collections.List<com.omnifret.gplayer.rendering.staves.MasterBarsRenderers>(
            )
            
            var systemIsFull: Boolean = false
            if (barsPerRow == -1.0 && system.width >= maxWidth && system.masterBarsRenderers.length != 0.0)
            {
                systemIsFull = true
            }
            else if (system.masterBarsRenderers.length == barsPerRow + 1.0)
            {
                systemIsFull = true
            }
            if (systemIsFull)
            {
                var reverted: com.omnifret.gplayer.rendering.staves.MasterBarsRenderers? = system.revertLastBar()
                if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(reverted)))
                {
                    this._barsFromPreviousSystem.push(reverted!!)
                    while (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(reverted)) && !reverted!!.canWrap) && system.masterBarsRenderers.length > 1))
                    {
                        reverted = system.revertLastBar()
                        if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(reverted)))
                        {
                            this._barsFromPreviousSystem.push(reverted!!)
                        }
                    }
                }
                system.isFull = true
                system.isLast = false
                this._barsFromPreviousSystem.reverse()
                return system
            }
            if (this._needsLineBreak(barIndex))
            {
                system.isFull = true
                system.isLast = false
                return system
            }
            system.x = 0.0
            barIndex++
        }
        system.isLast = endIndex == system.lastBarIndex
        return system
    }
    
    /**
     */
    private fun _needsLineBreak(barIndex: Double): Boolean{
        var anyTrackNeedsLineBreak: Boolean = false
        var allTracksNeedLineBreak: Boolean = true
        for (track in this.renderer.tracks!!)
        {
            if (com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(com.omnifret.gplayer.core.TypeHelper.isTruthy(track.lineBreaks)) && track.lineBreaks!!.has(barIndex + 1.0)))
            {
                anyTrackNeedsLineBreak = true
            }
            else 
            {
                allTracksNeedLineBreak = false
            }
        }
        return anyTrackNeedsLineBreak && allTracksNeedLineBreak
    }
    
    private val _maxWidth: Double
    get(){
        return this.scaledWidth - this.pagePadding!![(0).toInt()] - this.pagePadding!![(2).toInt()]
    }
    
    public constructor(renderer: com.omnifret.gplayer.rendering.ScoreRenderer)
        : super(renderer)
}

